<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\" />
    <None Remove="Parsers\" />
    <None Remove="Solvers\" />
    <None Remove="UI\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Parsers\" />
    <Folder Include="Solvers\" />
    <Folder Include="UI\" />
  </ItemGroup>
</Project>
