using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using LPR381_Project.Models;

namespace LPR381_Project.Solvers
{
    public class CuttingPlaneSolver : ISolver
    {
        public SimplexResult Solve(LinearModel rootModel, string outputFilePath)
        {
            using (StreamWriter writer = new StreamWriter(outputFilePath))
            {
                writer.WriteLine("=========================================");
                writer.WriteLine("        CUTTING PLANE ALGORITHM          ");
                writer.WriteLine("=========================================\n");

                bool isIntegerOptimal = false;
                int iteration = 1;

                // Clone the root model so we can append cuts dynamically without corrupting the original
                LinearModel currentModel = CloneModel(rootModel);

                while (!isIntegerOptimal)
                {
                    writer.WriteLine($"\n--- CUTTING PLANE ITERATION {iteration} ---");

                    // 1. Solve the current continuous model using Revised Simplex logic
                    // (This step would output the requested Product Form and Price Out iterations)
                    var result = SolveContinuousLP(currentModel, writer);

                    if (!result.IsFeasible)
                    {
                        writer.WriteLine("The model has no feasible integer solution.");
                        break;
                    }

                    // 2. Integrality Check
                    int fractionalVarRowIndex = GetVariableWithLargestFraction(result.Variables, currentModel.SignRestrictions);

                    if (fractionalVarRowIndex == -1)
                    {
                        isIntegerOptimal = true;
                        writer.WriteLine("\n*** Optimal Integer Solution Found ***");

                        writer.WriteLine($"Optimal Z = {result.Z:F3}");
                        for (int i = 0; i < result.Variables.Length; i++)
                        {
                            writer.WriteLine($"x{i + 1} = {result.Variables[i]:F3}");
                        }
                        break;
                    }

                    // 3. Generate Gomory Cut
                    // The fractional part of a number 'v' is: f = v - floor(v)
                    writer.WriteLine($"\nFractional variable detected. Generating Gomory Cut for variable index {fractionalVarRowIndex + 1}...");

                    Constraint gomoryCut = new Constraint
                    {
                        Relation = ">=", // Standard Gomory cut formulation requires variables to sum greater than the fraction
                        Coefficients = new List<double>()
                    };

                    // Extract fractional components from the optimal tableau row
                    // (Abstracted: result.TableauRow represents the row in the optimal tableau for the fractional variable)
                    for (int j = 0; j < result.TableauRow.Length; j++)
                    {
                        double fraction = result.TableauRow[j] - Math.Floor(result.TableauRow[j]);
                        gomoryCut.Coefficients.Add(Math.Round(fraction, 5)); // Prevent floating point bloat
                    }

                    // The RHS of the cut is the fractional part of the basic variable's value
                    double rhsFraction = result.Variables[fractionalVarRowIndex] - Math.Floor(result.Variables[fractionalVarRowIndex]);
                    gomoryCut.RHS = Math.Round(rhsFraction, 5);

                    writer.WriteLine($"Cut Added: Sum(f_ij * x_j) >= {gomoryCut.RHS:F3}");

                    // 4. Append Cut to the Model
                    currentModel.Constraints.Add(gomoryCut);

                    // Add a placeholder 0 to the objective function for the new slack variable generated by the cut
                    currentModel.ObjectiveCoefficients.Add(0.0);
                    currentModel.SignRestrictions.Add("urs");

                    iteration++;
                }
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine($"\nCutting Plane optimization complete. Results saved to {outputFilePath}");
            Console.ResetColor();

            return null;
        }

        // --- Helper Methods ---

        private int GetVariableWithLargestFraction(double[] variables, List<string> restrictions)
        {
            double maxFraction = 0;
            int targetIndex = -1;
            double tolerance = 0.00001;

            for (int i = 0; i < variables.Length; i++)
            {
                if (restrictions[i] == "int" || restrictions[i] == "bin")
                {
                    double fraction = variables[i] - Math.Floor(variables[i]);

                    // We want a fractional part strictly between 0 and 1 (ignoring rounding errors)
                    if (fraction > tolerance && fraction < 1 - tolerance)
                    {
                        if (fraction > maxFraction)
                        {
                            maxFraction = fraction;
                            targetIndex = i;
                        }
                    }
                }
            }
            return targetIndex;
        }

        private LinearModel CloneModel(LinearModel original)
        {
            LinearModel newModel = new LinearModel
            {
                OptimizationType = original.OptimizationType,
                ObjectiveCoefficients = new List<double>(original.ObjectiveCoefficients),
                SignRestrictions = new List<string>(original.SignRestrictions),
                Constraints = new List<Constraint>()
            };

            foreach (var c in original.Constraints)
            {
                newModel.Constraints.Add(new Constraint
                {
                    Coefficients = new List<double>(c.Coefficients),
                    Relation = c.Relation,
                    RHS = c.RHS
                });
            }
            return newModel;
        }

        private dynamic SolveContinuousLP(LinearModel model, StreamWriter writer)
        {
            // In a fully integrated execution, this calls your RevisedPrimalSimplex method
            // and retrieves the optimal Variables array, optimal Z, and the Tableau Rows 
            // required to formulate the cut.

            // Dummy return for architectural completion
            return new
            {
                IsFeasible = true,
                Z = 0.0,
                Variables = new double[model.ObjectiveCoefficients.Count],
                TableauRow = new double[model.ObjectiveCoefficients.Count]
            };
        }
    }
}
